version: '3'

services:
  #Vue Service
  app:
    build: ./
    image: desafio-app
    container_name: desafio-app
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    command: /bin/sh -c "npm install && npm run dev"